# Puedes eliminar la línea version si quieres quitar la advertencia
# version: "2.1"

services:
  api-gateway:
    container_name: demo_api_gateway
    build:
      context: ./servicios/api-gateway
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True

  pedidos:
    container_name: demo_orders
    build:
      context: ./servicios/pedidos
    ports:
      - "5001:5000"
    environment:
      - DEBUG=True

  articulos:
    container_name: demo_items
    build:
      context: ./servicios/articulos
    ports:
      - "5002:5000"
    environment:
      - DEBUG=True

  agregador:
    container_name: demo_aggregate
    build:
      context: ./servicios/agregador
    ports:
      - "5003:5000"
    environment:
      - DEBUG=True
